name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        backend: ["cpu"]
    steps:
    - uses: actions/checkout@v3
    - name: GithubPackages Login
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/geode-solutions/vtk:${{ matrix.python }}-${{ matrix.backend }}
        build-args: |
          PYTHON_VERSION=${{ matrix.python }} 
          BACKEND=${{ matrix.backend }}
